### ISSUE TITLE
twod exits on unexpected error

### ISSUE THREAD

**Issue by twisted-pear** [tablet-mode/twod#2]
After resetting my modem to check if twod would update my DNS entries I found this in my log:
`twod[11877]: Unexpected error while fetching external IP: HTTPSConnectionPool(host='icanhazip.com', port=443): Read timed out. (read timeout=16)`
While getting an error here was expected, what was not is that twod terminated.

Twod should keep running no matter what errors it encounters and just retry after the next interval.

**Comment by t4k1t** [comment]
Indeed `twod` wasn't catching timeouts on HTTP connections. Fixed in version 0.3.2.
